// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2xbs0OZ6QdQRnghs7itEa7DlFNqLMZ7k',
    appId: '1:618795565915:web:490a6c4bea12111cf5107e',
    messagingSenderId: '618795565915',
    projectId: 'instagramclone-755a1',
    authDomain: 'instagramclone-755a1.firebaseapp.com',
    storageBucket: 'instagramclone-755a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Y7JqCzWqxP4xc2PEi2_4FY7IY49qmwU',
    appId: '1:618795565915:android:78f409b99da626aaf5107e',
    messagingSenderId: '618795565915',
    projectId: 'instagramclone-755a1',
    storageBucket: 'instagramclone-755a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYDpKWCwvpogs0o13A6nJJeSGZis_pN6Q',
    appId: '1:618795565915:ios:0d7712a5e1ea1b61f5107e',
    messagingSenderId: '618795565915',
    projectId: 'instagramclone-755a1',
    storageBucket: 'instagramclone-755a1.firebasestorage.app',
    iosBundleId: 'com.example.instagramCloneFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYDpKWCwvpogs0o13A6nJJeSGZis_pN6Q',
    appId: '1:618795565915:ios:0d7712a5e1ea1b61f5107e',
    messagingSenderId: '618795565915',
    projectId: 'instagramclone-755a1',
    storageBucket: 'instagramclone-755a1.firebasestorage.app',
    iosBundleId: 'com.example.instagramCloneFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2xbs0OZ6QdQRnghs7itEa7DlFNqLMZ7k',
    appId: '1:618795565915:web:72913b39adf146e2f5107e',
    messagingSenderId: '618795565915',
    projectId: 'instagramclone-755a1',
    authDomain: 'instagramclone-755a1.firebaseapp.com',
    storageBucket: 'instagramclone-755a1.firebasestorage.app',
  );

}